FROM node:22-alpine3.19 as developer

WORKDIR /app

COPY package*.json ./ 

COPY tsconfig.json . 

COPY .env.development . 

COPY ecosystem.config.js .

RUN npm install 

COPY . .

CMD [ "npm","run","dev" ]
