openapi: 3.0.3
info:
  title: API With BTL
  description: Api bài tập lớn
  termsOfService: http://swagger.io/terms/
  contact:
    email: duong2lophot@gmail.com
  license:
    name: Apache 2.0
  version: 1.0.11
servers:
  - url: http://localhost:3000/api/v1
tags:
  - name: auth
    description: Đăng ký tài khoản

paths:
  /register:
    post:
      tags:
        - auth
      requestBody:
        description: Đăng ký tài khoản
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  minLength: 1
                  maxLength: 255
                  description: name phải nhập tối thiểu 1 kí tự và max là 255 kí tự
                  example: vudinhduong
                password:
                  type: string
                  minLength: 5
                  maxLength: 25
                  description: password phải nhập ít nhất 5 kí tự và nhiều nhất 25 kí tự
                  example: 12345
                email:
                  type: string
                  example: duong@gmail.com
                  description: phải nhập là email
                date_of_birth:
                  type: string
                  format: date
                  example: 1996-0204
                  description: kiểu IOString8601
        required: true
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: register successfully
                  data:
                    type: object
                    properties:
                      access_token:
                        type: string
                        example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNjUzZTM3OTE2NmE3N2YyM2NjODZjMjQ5IiwiaWF0IjoxNjk4NTc2MjczLCJleHAiOjE2OTg1Nzk4NzN9.yyo6Y8Kxe8r9SHoS2HavjcfTTAq8o3V_DxOJV-juvhQ
                      refresh_token:
                        type: string
                        example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNjUzZTM3OTE2NmE3N2YyM2NjODZjMjQ5IiwiaWF0IjoxNjk4NTc2MjczLCJleHAiOjE2OTg1Nzk4NzN9.yyo6Y8Kxe8r9SHoS2HavjcfTTAq8o3V_DxOJV-juvhQ
        "401":
          description: Invalid ID supplied
          content:
            application/json:
              schema:
                type: object
                properties:
                  email:
                    type: string
                    example: email đã tồn tại
  /email_verify_token/{token}:
    post:
      tags:
        - auth
      parameters:
        - name: token
          in: path
          description: token
          required: true
          schema:
            type: string
            example: đkr3i4u3d39438
      responses:
        "200":
          description: verify email
          content:
            application/json:
              schema:
                properties:
                  message:
                    type: string
                    example: verify email successfuly
        "402":
          description: error token hết hạn
          content:
            application/json:
              schema:
                properties:
                  message:
                    type: string
                    example: token đã hết hạn hoặc không đúng
  /login:
    post:
      tags:
        - auth
      requestBody:
        description: Đăng nhập
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  example: duong@gmail.com
                  description: phải nhập đúng là email
                password:
                  type: string
                  example: 123456
                  minLength: 5
                  maxLength: 25
                  description: phải nhập tối thiểu 5 kí tự và tối đa 25 kí tự

      responses:
        "200":
          description: response
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: login successfully
                  data:
                    type: object
                    properties:
                      access_token:
                        type: string
                        example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNjUzZTM3OTE2NmE3N2YyM2NjODZjMjQ5IiwiaWF0IjoxNjk4NTc2MjczLCJleHAiOjE2OTg1Nzk4NzN9.yyo6Y8Kxe8r9SHoS2HavjcfTTAq8o3V_DxOJV-juvhQ
                      refresh_token:
                        type: string
                        example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNjUzZTM3OTE2NmE3N2YyM2NjODZjMjQ5IiwiaWF0IjoxNjk4NTc2MjczLCJleHAiOjE2OTg1Nzk4NzN9.yyo6Y8Kxe8r9SHoS2HavjcfTTAq8o3V_DxOJV-juvhQ
                      user:
                        type: object
                        properties:
                          name:
                            type: string
                            example: ngocduong
                          email:
                            type: string
                            example: ngocduong@gmail.com
                          date_of_birth:
                            type: string
                            format: date
                            example: 1996-01-01
                          username:
                            type: string
                          bio:
                            type: string
                          website:
                            type: string
                          avatar:
                            type: string
                          cover_photo:
                            type: string
                          location:
                            type: string
                          _id:
                            type: string
                            format: ObjectID
                            example: 653e5b5630f1766c6822d46a
        "401":
          description: email không đúng hoặc mật khẩu không đúng
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: email của bạn không đúng
  /logout:
    post:
      tags:
        - auth
      requestBody:
        description: logout
        content:
          application/json:
            schema:
              type: object
              properties:
                refresh_token:
                  type: string
                  example: kdfdfejrokdfjdkfj3489rudkjfffffffffff
      responses:
        "200":
          description: response
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: logout successfully

        "401":
          description: token không đúng hoặc đã hết hạn
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: token không đúng hoặc hết hạn

  /refresh_token:
    post:
      tags:
        - auth
      requestBody:
        description: refresh token
        content:
          application/json:
            schema:
              properties:
                refresh_token:
                  type: string
                  example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNjUzZWE5YzAyM2MwODM1ZTMxMjMzMGY3IiwiaWF0IjoxNjk4NjA2MDU1LCJleHAiOjE2OTg2NDIwNTV9._UGvagSXmLjQ1HJR8FYAHcYrjkWs9oX11G60s4mbHjE
        required: true
      responses:
        "200":
          description: response refresh_token
          content:
            application/json:
              schema:
                properties:
                  message:
                    type: string
                    example: refresh_token successfully
                  data:
                    properties:
                      access_token:
                        type: string
                        example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNjUzZWE5YzAyM2MwODM1ZTMxMjMzMGY3IiwiaWF0IjoxNjk4NjA2MDU1LCJleHAiOjE2OTg2NDIwNTV9._UGvagSXmLjQ1HJR8FYAHcYrjkWs9oX11G60s4mbHjE
                      refresh_token:
                        type: string
                        example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiNjUzZWE5YzAyM2MwODM1ZTMxMjMzMGY3IiwiaWF0IjoxNjk4NjA2MDU1LCJleHAiOjE2OTg2NDIwNTV9._UGvagSXmLjQ1HJR8FYAHcYrjkWs9oX11G60s4mbHjE
        "401":
          description: error token hết hạn
          content:
            application/json:
              schema:
                properties:
                  message:
                    type: string
                    example: token đã hết hạn hoặc không đúng
  /forgot_password:
    post:
      tags:
        - auth
      requestBody:
        description: forgot password
        content:
          application/json:
            schema:
              properties:
                email:
                  type: string
                  example: duong@gmail.com
        required: true
      responses:
        "200":
          description: forgot_password
          content:
            application/json:
              schema:
                properties:
                  message:
                    type: string
                    example: kiểm tra email để xác nhận
                  data:
                    properties:
                      _id:
                        type: string
                        format: ObjectID
                        example: 653ea9c023c0835e312330f7

        "401":
          description: error token hết hạn
          content:
            application/json:
              schema:
                properties:
                  message:
                    type: string
                    example: token đã hết hạn hoặc không đúng

  /forgot_password/{_id}:
    post:
      tags:
        - auth
      parameters:
        - name: _id
          in: path
          description: token
          required: true
          schema:
            type: string
            example: 653ea9c023c0835e312330f7
      requestBody:
        description: check ma
        content:
          application/json:
            schema:
              properties:
                forgot_password_token:
                  type: string
                  example: 123456
        required: true
      responses:
        "200":
          description: forgot_password_token
          content:
            application/json:
              schema:
                properties:
                  message:
                    type: string
                    example: forgot_password successfully
                  data:
                    properties:
                      _id:
                        type: string
                        format: ObjectID
                        example: 653ea9c023c0835e312330f7

        "401":
          description: error token hết hạn
          content:
            application/json:
              schema:
                properties:
                  message:
                    type: string
                    example: token đã hết hạn hoặc không đúng
  /reset_password/{_id}:
    post:
      tags:
        - auth
      parameters:
        - name: _id
          in: path
          description: _id
          required: true
          schema:
            type: string
            example: 653ea9c023c0835e312330f7
      requestBody:
        description: reset_password
        content:
          application/json:
            schema:
              properties:
                password:
                  type: string
                  example: 123456
                confirm_password:
                  type: string
                  example: 123456
        required: true
      responses:
        "200":
          description: reset_pasword
          content:
            application/json:
              schema:
                properties:
                  message:
                    type: string
                    example: reset password successfully

        "401":
          description: error token hết hạn
          content:
            application/json:
              schema:
                properties:
                  message:
                    type: string
                    example: token đã hết hạn hoặc không đúng
  /getMe:
    get:
      tags:
        - auth
      responses:
        "200":
          description: get me
          content:
            application/json:
              schema:
                properties:
                  message:
                    type: string
                    example: reset password successfully
                  data:
                    properties:
                      _id:
                        type: string
                        format: ObjectID
                        example: dfkdfjeire33493
                      name:
                        type: string
                        example: ngọc dương
                      email:
                        type: string
                        example: duong2@gmail.com
                      bio:
                        type: string
                        example: xin chào
                      website:
                        type: string
                        example: xin chào

        "401":
          description: error token hết hạn
          content:
            application/json:
              schema:
                properties:
                  message:
                    type: string
                    example: token đã hết hạn hoặc không đúng
  /update_me:
    patch:
      tags:
        - auth
      requestBody:
        description: update me
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/updateMe"
        required: true
      security:
        - BearerAuth: []
      responses:
        "200":
          description: get me
          content:
            application/json:
              schema:
                properties:
                  message:
                    type: string
                    example: reset password successfully
                  data:
                    properties:
                      _id:
                        type: string
                        format: ObjectID
                        example: dfkdfjeire33493
                      name:
                        type: string
                        example: ngọc dương
                      email:
                        type: string
                        example: duong2@gmail.com
                      bio:
                        type: string
                        example: xin chào
                      website:
                        type: string
                        example: xin chào

        "401":
          description: error token hết hạn
          content:
            application/json:
              schema:
                properties:
                  message:
                    type: string
                    example: token đã hết hạn hoặc không đúng
  /follow/{id}:
    post:
      tags:
        - auth
      parameters:
        - name: id
          in: path
          description: token
          required: true
          schema:
            type: string
            example: 653ea9c023c0835e312330f7
      responses:
        "200":
          description: follower
          content:
            application/json:
              schema:
                properties:
                  message:
                    type: string
                    example: follower successfully

        "401":
          description: error token hết hạn
          content:
            application/json:
              schema:
                properties:
                  message:
                    type: string
                    example: token đã hết hạn hoặc không đúng
  /unfollow/{id}:
    post:
      tags:
        - auth
      parameters:
        - name: id
          in: path
          description: token
          required: true
          schema:
            type: string
            example: 653ea9c023c0835e312330f7
      responses:
        "200":
          description: unfollower
          content:
            application/json:
              schema:
                properties:
                  message:
                    type: string
                    example: unfollower successfully
        "401":
          description: error token hết hạn
          content:
            application/json:
              schema:
                properties:
                  message:
                    type: string
                    example: token đã hết hạn hoặc không đúng
components:
  schemas:
    updateMe:
      type: object
      properties:
        name:
          type: string
          example: ngọc dương
        email:
          type: string
          example: duong2@gmail.com
        bio:
          type: string
          example: xin chào
        website:
          type: string
          example: xin chào
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
